### ISSUE TITLE
Neither taking input from file nor producing output in file 

### ISSUE THREAD

**Issue by mkmohitkmr** [codeict/CP-VSCode-Setup#3]
I followed the youtube video to setup this on my Ubuntu 20.04 laptop. I am not able to accept input from file. Also, on hard coding some values, I am not even able to get the output in output.txt file. Please help resolve this issue.

**Comment by codeict** [comment]
Hi, I will need more details than this. Can you mail me at codeicted@gmail.com

**Comment by codeict** [comment]
Since there is no response, closing this issue.
