### ISSUE TITLE
cStandard 

### ISSUE THREAD

**Issue by Ogscar** [codeict/CP-VSCode-Setup#4]
I'm having problems with the cStandard not beeing accepted. 

![image](https://user-images.githubusercontent.com/85513392/121063907-336af900-c7c7-11eb-8114-f3351817766c.png)

**Comment by codeict** [comment]
Hey, in my experience these are corrected automatically by vscode in case of a version difference.
Please try these things and let me know:

1. Check that the `compilerPath` on line 13 is correct.
2. Try removing the cStandard and cppStandard

If both of these don't work, then it is a problem with the compiler. 
You were supposed to install the x86 version of mingw, not the i686 version. Do refer to the windows installation YouTube video.

This should solve the problem. Feel free to revert if that doesn't work for you.

Cheers

**Comment by Ogscar** [comment]
Hi! I downloaded the correct mingw version and removed the cStandard and cppStandard so that problem is gone but when i try to  execute the program in your video i don't get any output. 
![image](https://user-images.githubusercontent.com/85513392/121071136-dde71a00-c7cf-11eb-96d7-5e719dc10d3d.png)
