### ISSUE TITLE
Program not taking input from file nor producing output in file

### ISSUE THREAD

**Issue by Ogscar** [codeict/CP-VSCode-Setup#5]
Hi, When i run the program from your video i don't get any output in output.txt.  

![image](https://user-images.githubusercontent.com/85513392/121146854-a06ea500-c840-11eb-9872-25c99c1f75e8.png)

**Comment by codeict** [comment]
Please check the sample code, it first takes in `t` and then runs solve.

Either change the code or set the input as
`2
1
2`

**Comment by Ogscar** [comment]
Still no output
![image](https://user-images.githubusercontent.com/85513392/121152382-6e137680-c845-11eb-8d3b-93116b11d982.png)

**Comment by codeict** [comment]
Can you join me [here](https://meet.google.com/vvy-bgaj-gqw)

**Comment by Ogscar** [comment]
just saw in the therminal that i get "terminated with exit code 1"

**Comment by codeict** [comment]
Okay, so is it working now?

**Comment by Ogscar** [comment]
No sadly not. 
![image](https://user-images.githubusercontent.com/85513392/121154237-1a099180-c847-11eb-9cb6-8494c4dcdb83.png)

**Comment by codeict** [comment]
Can you please join me on the call so that we can debug it faster? 
https://meet.google.com/vvy-bgaj-gqw

**Comment by codeict** [comment]
Please try making this change in tasks.json: 
![image](https://user-images.githubusercontent.com/37595244/121161969-648a0e80-c845-11eb-9321-9c0efa708bd9.png)

If it still does not work, you should update your powershell vesion, the problem seems to be there.
